#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenCV.SDKDemo.Resource", IsApplication=true)]

namespace OpenCV.SDKDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int any = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int back = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int calibrate = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int calibration = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int cameraCalibration = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int cameraControl = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int cameraPreview = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int camera_calibration_java_surface_view = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int colorBlobDetection = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int color_blob_detection_activity_surface_view = 2131165189;
			
			// aapt resource value: 0x7f070016
			public const int comparison = 2131165206;
			
			// aapt resource value: 0x7f07000c
			public const int faceDetection = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int fd_activity_surface_view = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int front = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int imageManipulations = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int image_manipulations_activity_surface_view = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int mixedProcessing = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int preview_mode = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int puzzle = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int surfaceView = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int tutorial2_activity_surface_view = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int tutorial3_activity_java_surface_view = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int undistortion = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int camera_calibration_surface_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraPreview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int color_blob_detection_surface_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int face_detect_surface_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int image_manipulations_surface_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Puzzle = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int tutorial2_surface_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int tutorial3_surface_view = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int calibration = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int lbpcascade_frontalface = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int action_calibrate = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int calibrating = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int calibration = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int calibration_successful = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int calibration_unsuccessful = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int comparison = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int more_samples = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int original = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int please_wait = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int preview_mode = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int undistorted = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int undistortion = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
