#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenCV.SDKDemo.Resource", IsApplication=true)]

namespace OpenCV.SDKDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int any = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int back = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int calibrate = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int calibration = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int cameraCalibration = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int cameraControl = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int cameraPreview = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int camera_calibration_java_surface_view = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int colorBlobDetection = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int color_blob_detection_activity_surface_view = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int comparison = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int faceDetection = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int front = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int imageManipulations = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int mixedProcessing = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int preview_mode = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int puzzle = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int surfaceView = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int undistortion = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraCalibration = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraPreview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int color_blob_detection_surface_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Puzzle = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int calibration = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int action_calibrate = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int calibrating = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int calibration = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int calibration_successful = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int calibration_unsuccessful = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int comparison = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int more_samples = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int original = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int please_wait = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int preview_mode = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int undistorted = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int undistortion = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
