#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenCV.SDKDemo.Resource", IsApplication=true)]

namespace OpenCV.SDKDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int any = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int back = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int cameraCalibration = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int cameraControl = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int cameraPreview = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int colorBlobDetection = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int faceDetection = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int front = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int imageManipulations = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int mixedProcessing = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int puzzle = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int surfaceView = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraPreview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Puzzle = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
